[[repos]]
repo = "builtin"

[[repos.hooks]]
id = "check-added-large-files"

[[repos.hooks]]
id = "check-symlinks"


[[repos]]
repo = "local"

[[repos.hooks]]
id = "cargo-fmt"
name = "format code"
language = "system"
entry = "cargo fmt"
pass_filenames = false

[[repos.hooks]]
id = "cargo-clippy"
name = "lint"
language = "system"
entry = "cargo clippy --workspace --all-features -- -D warnings"
pass_filenames = false
